In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression

In [ ]:
class LinReg:
  def __init__(self):
    self.c = None
    self.m = None

  def fitt(self,x , y):
    self.x = np.array(x)
    self.y = np.array(y)
    num = sum((self.x - self.x.mean())*(self.y - self.y.mean()))
    den = sum((self.x - self.x.mean())**2)
    m = num / den
    c = self.y.mean() - m* self.x.mean()
    self.m = m
    self.c = c
    self.y = self.m * self.x.mean() + self.c


  def predd(self,x):
    x = np.array(x)
    self.y = self.m * x.mean() + self.c
    return self.y


In [ ]:
le = LinReg()

In [ ]:
x,y = make_regression(n_samples=200, n_features=1, n_informative=1, n_targets=1)

In [ ]:
x

array([[-1.03464693],
       [-1.143816  ],
       [-0.50413935],
       [ 0.38734476],
       [ 0.37554938],
       [ 0.33824893],
       [ 1.63589134],
       [-1.0440242 ],
       [ 1.14230827],
       [ 0.18670387],
       [ 0.00299206],
       [ 0.50802083],
       [ 0.35706381],
       [ 2.10509231],
       [ 0.70361164],
       [ 0.33572717],
       [ 0.59998517],
       [-1.2953385 ],
       [ 1.35037234],
       [-1.56318972],
       [ 0.6685637 ],
       [ 1.39712957],
       [ 0.1938013 ],
       [ 0.2897363 ],
       [ 1.82191407],
       [-0.84964199],
       [ 1.70812075],
       [-2.74283046],
       [ 0.37203605],
       [ 0.56832424],
       [ 1.33499278],
       [-0.88587986],
       [-1.50735238],
       [-0.97619923],
       [-0.97874475],
       [-1.32275534],
       [-0.89502101],
       [-1.47716878],
       [ 0.27016269],
       [-1.92733221],
       [ 0.40930392],
       [ 1.44732355],
       [ 0.57533753],
       [-0.0039863 ],
       [-0.76793959],
       [ 0

In [ ]:
y

array([ -8.35501487,  -9.2365806 ,  -4.07104266,   3.12789913,
         3.03264872,   2.73143891,  13.21020349,  -8.43073856,
         9.22440531,   1.5076772 ,   0.02416159,   4.10238653,
         2.88337345,  16.99911064,   5.68182785,   2.71107506,
         4.84502   , -10.46016006,  10.90457115, -12.62312102,
         5.39880758,  11.28214662,   1.56499065,   2.33968809,
        14.71238042,  -6.86105696,  13.79347284, -22.1489947 ,
         3.00427775,   4.58935058,  10.78037762,  -7.15368615,
       -12.17222148,  -7.8830361 ,  -7.90359178, -10.68155744,
        -7.22750306, -11.92848188,   2.18162662, -15.5636564 ,
         3.30522447,  11.68747472,   4.64598457,  -0.03219029,
        -6.20129104,   3.798486  ,   3.6999384 ,   4.94496355,
        -0.53394981,  -3.58794242,   7.4120516 ,  -0.19142973,
         4.51763897,   3.36812034,  -3.38819015, -12.88331967,
        -2.02076898,   7.22011306, -10.88798757,  10.01339682,
        -7.3218891 ,  -5.81963686,  -8.80458878, -16.19

In [ ]:
r = le.fitt(x,y)

In [ ]:
p = le.predd([10,39,3.3,3])

In [ ]:
p

array([-0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24234566,
       -0.24234566, -0.24234566, -0.24234566, -0.24234566, -0.24