In [ ]:
# multiple classes logistic regression
#softmax function
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
data = sns.load_dataset('iris')

In [ ]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
new_data = data[['petal_length','sepal_length','species']]

In [ ]:
new_data

petal_length  sepal_length    species
0             1.4           5.1     setosa
1             1.4           4.9     setosa
2             1.3           4.7     setosa
3             1.5           4.6     setosa
4             1.4           5.0     setosa
..            ...           ...        ...
145           5.2           6.7  virginica
146           5.0           6.3  virginica
147           5.2           6.5  virginica
148           5.4           6.2  virginica
149           5.1           5.9  virginica

[150 rows x 3 columns]

In [ ]:
encoder = LabelEncoder()
new_data['species'] = encoder.fit_transform(new_data['species'])

<ipython-input-13-003070c53c46>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['species'] = encoder.fit_transform(new_data['species'])


In [ ]:
new_data

petal_length  sepal_length  species
0             1.4           5.1        0
1             1.4           4.9        0
2             1.3           4.7        0
3             1.5           4.6        0
4             1.4           5.0        0
..            ...           ...      ...
145           5.2           6.7        2
146           5.0           6.3        2
147           5.2           6.5        2
148           5.4           6.2        2
149           5.1           5.9        2

[150 rows x 3 columns]

In [ ]:
x = new_data.drop(columns=['species'])
y = new_data['species']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
lg = LogisticRegression(multi_class='multinomial')
model = lg.fit(x_train, y_train)
pred = model.predict(x_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [ ]:
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
accuracy_score(y_test, pred)

1.0

In [ ]:
confusion_matrix(y_test, pred)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [ ]:
x,y = make_classification(n_samples=1000, n_features=2, n_informative=2, n_classes=3,n_clusters_per_class=1,n_redundant=0, n_repeated=0)
# perplexity

In [ ]:
x_new, x_tNew, y_new, y_tNew = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
lg = LogisticRegression(multi_class='multinomial')
model = lg.fit(x_new, y_new)
pred = model.predict(x_tNew)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [ ]:
pred

array([1, 0, 0, 0, 1, 0, 2, 1, 0, 2, 0, 2, 2, 0, 1, 0, 2, 0, 1, 2, 1, 1,
       2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 1, 0, 2, 1, 0, 0, 0, 0, 1, 0, 1, 2,
       0, 0, 1, 1, 2, 0, 0, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 1, 1, 2, 0,
       0, 2, 0, 2, 2, 1, 0, 0, 1, 0, 0, 2, 0, 2, 2, 2, 0, 1, 2, 1, 0, 2,
       0, 0, 2, 1, 0, 1, 1, 0, 2, 0, 2, 1, 2, 0, 0, 1, 0, 1, 2, 2, 0, 2,
       0, 1, 2, 2, 0, 2, 1, 0, 0, 2, 1, 2, 1, 0, 2, 1, 0, 2, 1, 1, 1, 1,
       0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 2, 1, 0, 2, 2, 0, 2, 2,
       0, 2, 2, 1, 0, 1, 2, 2, 2, 1, 1, 2, 0, 0, 1, 1, 2, 1, 1, 1, 1, 2,
       2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 2])

In [ ]:
accuracy_score(y_tNew, pred)

0.91

In [ ]:
confusion_matrix(y_tNew, pred)

array([[66,  3,  2],
       [ 6, 50,  6],
       [ 1,  0, 66]])